language: rust
addons:
  apt:
    packages:
    - libdiscid0-dev
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo test --verbose
  - rustfmt --check --edition 2018 {examples,src}/*.rs
